// ============================================================
// DUMMY DATA – Replace with API responses when backend is ready
// ============================================================

export const currentUser = {
  id: 'u001',
  name: 'Arjun Sharma',
  mobile: '+91 98765 43210',
  email: 'arjun.sharma@email.com',
  dob: '1995-04-12',
  memberSince: 'Jan 2024',
  avatar: null, // replace with require('../../assets/images/avatar.png')
  emergencyContact: 'Priya Sharma – +91 91234 56789',
  healthHistory: 'No pre-existing conditions',
  injuryHistory: 'Right knee sprain (2022) – recovered',
};

export const membership = {
  type: 'ELITE',
  status: 'ACTIVE',
  validFrom: '2026-01-01',
  validTill: '2026-07-01',
  daysLeft: 128,
  planFeatures: [
    'Unlimited gym access',
    'Free locker',
    '2 PT sessions / month',
    'Café discount – 10%',
  ],
};

export const buildCoins = {
  balance: 2450,
  totalEarned: 5000,
  totalSpent: 2550,
  transactions: [
    { id: 't1', type: 'credit', amount: 500, desc: 'Admin allocation', date: '20 Feb 2026' },
    { id: 't2', type: 'debit', amount: 120, desc: 'Protein Shake – Café', date: '19 Feb 2026' },
    { id: 't3', type: 'debit', amount: 250, desc: 'Chicken Bowl – Café', date: '17 Feb 2026' },
    { id: 't4', type: 'credit', amount: 1000, desc: 'Monthly coins added', date: '01 Feb 2026' },
    { id: 't5', type: 'debit', amount: 80, desc: 'Protein Bar – Café', date: '14 Feb 2026' },
  ],
};

export const announcements = [
  {
    id: 'a1',
    title: '🏆 Build Games – March Edition',
    subtitle: 'Internal fitness competition. Register before 28 Feb.',
    type: 'event',
    date: '23 Feb 2026',
    urgent: false,
  },
  {
    id: 'a2',
    title: '⚡ New Equipment Arrived',
    subtitle: 'Cable machine row + hack squat now live on Floor 2.',
    type: 'update',
    date: '21 Feb 2026',
    urgent: false,
  },
  {
    id: 'a3',
    title: '🚨 Holiday Timings – Holi',
    subtitle: 'Gym open 6AM–2PM on 14 March. Plan accordingly.',
    type: 'alert',
    date: '20 Feb 2026',
    urgent: true,
  },
];

export const trainers = [
  {
    id: 'tr1',
    name: 'Karan Mehta',
    specialisation: 'Strength & Hypertrophy',
    experience: '8 years',
    rating: 4.9,
    clients: 24,
    bio: 'Certified strength coach specialising in powerlifting and muscle building. NSCA-CSCS certified with a background in competitive powerlifting.',
    tags: ['Powerlifting', 'Hypertrophy', 'Nutrition'],
    image: null, // replace with require('../../assets/images/trainer1.png')
    available: true,
  },
  {
    id: 'tr2',
    name: 'Sneha Reddy',
    specialisation: 'Functional Fitness & HIIT',
    experience: '6 years',
    rating: 4.8,
    clients: 18,
    bio: 'Functional fitness expert and CrossFit L2 trainer. Passionate about injury-free movement and athletic performance.',
    tags: ['CrossFit', 'HIIT', 'Mobility'],
    image: null,
    available: true,
  },
  {
    id: 'tr3',
    name: 'Rahul Desai',
    specialisation: 'Weight Loss & Cardio',
    experience: '5 years',
    rating: 4.7,
    clients: 21,
    bio: 'Specialises in metabolic conditioning and sustainable fat loss. ACE certified personal trainer.',
    tags: ['Fat Loss', 'Cardio', 'Conditioning'],
    image: null,
    available: false,
  },
  {
    id: 'tr4',
    name: 'Anjali Nair',
    specialisation: 'Yoga & Flexibility',
    experience: '7 years',
    rating: 4.9,
    clients: 15,
    bio: 'RYT-500 certified yoga instructor with expertise in functional flexibility and mindfulness-based training.',
    tags: ['Yoga', 'Flexibility', 'Mindfulness'],
    image: null,
    available: true,
  },
];

export const cafeCategories = ['All', 'Shakes', 'Meals', 'Snacks', 'Supplements'];

export const cafeItems = [
  // ── Shakes ────────────────────────────────────────────────
  {
    id: 'c1',
    name: 'Whey Protein Shake',
    category: 'Shakes',
    price: 120,
    description: 'Cold-blended whey isolate with banana and oats. High protein post-workout shake.',
    calories: 320,
    protein: '35g',
    carbs: '28g',
    fat: '4g',
    suitableFor: 'Post-workout recovery',
    tag: 'Best Seller',
    image: null,
    available: true,
  },
  {
    id: 'c2',
    name: 'Mass Gainer Shake',
    category: 'Shakes',
    price: 150,
    description: 'High-calorie blend with oats, peanut butter, banana and whole milk for mass building.',
    calories: 620,
    protein: '28g',
    carbs: '72g',
    fat: '12g',
    suitableFor: 'Bulking / Mass gain',
    tag: null,
    image: null,
    available: true,
  },
  {
    id: 'c3',
    name: 'Green Detox Shake',
    category: 'Shakes',
    price: 100,
    description: 'Spinach, cucumber, lemon, ginger blended with cold water. Clean and refreshing.',
    calories: 80,
    protein: '4g',
    carbs: '14g',
    fat: '1g',
    suitableFor: 'Fat loss / Cardio days',
    tag: 'Healthy',
    image: null,
    available: true,
  },
  {
    id: 'c4',
    name: 'Mango Lassi Pro',
    category: 'Shakes',
    price: 110,
    description: 'Greek yoghurt, mango puree and honey with added casein for slow protein release.',
    calories: 280,
    protein: '22g',
    carbs: '36g',
    fat: '3g',
    suitableFor: 'Anytime / Rest day',
    tag: null,
    image: null,
    available: true,
  },
  // ── Meals ─────────────────────────────────────────────────
  {
    id: 'c5',
    name: 'Grilled Chicken Bowl',
    category: 'Meals',
    price: 250,
    description: 'Grilled chicken breast with brown rice, steamed broccoli and garlic sauce.',
    calories: 480,
    protein: '48g',
    carbs: '40g',
    fat: '8g',
    suitableFor: 'Post-workout / Lean bulking',
    tag: 'Chef Pick',
    image: null,
    available: true,
  },
  {
    id: 'c6',
    name: 'Egg White Omelette',
    category: 'Meals',
    price: 180,
    description: '5 egg-white omelette with veggies, served with whole wheat toast.',
    calories: 320,
    protein: '38g',
    carbs: '22g',
    fat: '6g',
    suitableFor: 'Pre-workout breakfast',
    tag: null,
    image: null,
    available: true,
  },
  {
    id: 'c7',
    name: 'Paneer Power Bowl',
    category: 'Meals',
    price: 220,
    description: 'Grilled paneer cubes with quinoa, roasted vegetables and mint chutney.',
    calories: 420,
    protein: '32g',
    carbs: '38g',
    fat: '14g',
    suitableFor: 'Vegetarian / Muscle building',
    tag: 'Veg',
    image: null,
    available: true,
  },
  {
    id: 'c8',
    name: 'Tuna Salad Wrap',
    category: 'Meals',
    price: 200,
    description: 'Tuna, avocado and greens in a whole wheat wrap with lemon-pepper dressing.',
    calories: 380,
    protein: '42g',
    carbs: '28g',
    fat: '10g',
    suitableFor: 'Fat loss / Shred phase',
    tag: null,
    image: null,
    available: false,
  },
  // ── Snacks ────────────────────────────────────────────────
  {
    id: 'c9',
    name: 'Protein Bar (Choco)',
    category: 'Snacks',
    price: 80,
    description: 'Dark chocolate & almond protein bar. 20g protein, low sugar.',
    calories: 210,
    protein: '20g',
    carbs: '18g',
    fat: '7g',
    suitableFor: 'On-the-go snack',
    tag: 'Low Sugar',
    image: null,
    available: true,
  },
  {
    id: 'c10',
    name: 'Roasted Makhana',
    category: 'Snacks',
    price: 60,
    description: 'Fox nuts roasted with Himalayan salt and black pepper. High protein, low carb snack.',
    calories: 140,
    protein: '10g',
    carbs: '16g',
    fat: '3g',
    suitableFor: 'Anytime / Keto friendly',
    tag: 'Keto',
    image: null,
    available: true,
  },
  {
    id: 'c11',
    name: 'Boiled Egg Platter',
    category: 'Snacks',
    price: 70,
    description: '4 boiled eggs with black pepper and pink salt. Quick protein hit.',
    calories: 280,
    protein: '24g',
    carbs: '2g',
    fat: '18g',
    suitableFor: 'Pre/Post workout',
    tag: null,
    image: null,
    available: true,
  },
  // ── Supplements ───────────────────────────────────────────
  {
    id: 'c12',
    name: 'Creatine Monohydrate',
    category: 'Supplements',
    price: 90,
    description: '5g unflavoured creatine monohydrate (single dose sachet). Strength and power boost.',
    calories: 0,
    protein: '0g',
    carbs: '0g',
    fat: '0g',
    suitableFor: 'Strength training / Pre workout',
    tag: 'Performance',
    image: null,
    available: true,
  },
  {
    id: 'c13',
    name: 'BCAA Drink',
    category: 'Supplements',
    price: 100,
    description: 'Watermelon-flavoured BCAA drink, 7g BCAAs in 2:1:1 ratio. Prevents muscle breakdown.',
    calories: 15,
    protein: '7g',
    carbs: '1g',
    fat: '0g',
    suitableFor: 'Intra-workout / Endurance',
    tag: null,
    image: null,
    available: true,
  },
  {
    id: 'c14',
    name: 'Pre-Workout Shot',
    category: 'Supplements',
    price: 130,
    description: 'Concentrated pre-workout with caffeine, beta-alanine and nitric oxide boosters.',
    calories: 25,
    protein: '0g',
    carbs: '5g',
    fat: '0g',
    suitableFor: 'Heavy lifting / HIIT sessions',
    tag: 'Energy',
    image: null,
    available: true,
  },
];

export const notifications = [
  {
    id: 'n1',
    title: 'Membership Reminder',
    body: 'Your membership expires in 30 days. Contact reception to renew.',
    type: 'membership',
    time: '2 hours ago',
    read: false,
  },
  {
    id: 'n2',
    title: 'Order Confirmed',
    body: 'Your order – Grilled Chicken Bowl has been placed. 250 Build Coins deducted.',
    type: 'cafe',
    time: 'Yesterday, 1:30 PM',
    read: false,
  },
  {
    id: 'n3',
    title: 'Build Coins Credited',
    body: '500 Build Coins have been added to your account by Admin.',
    type: 'coins',
    time: '2 days ago',
    read: true,
  },
  {
    id: 'n4',
    title: 'New Equipment Announcement',
    body: 'Cable machine row + hack squat now available on Floor 2. Try them out!',
    type: 'announcement',
    time: '3 days ago',
    read: true,
  },
  {
    id: 'n5',
    title: 'Access Granted',
    body: 'Locker #14 opened successfully at 6:42 AM.',
    type: 'access',
    time: '3 days ago',
    read: true,
  },
];

export const membershipOffers = [
  {
    id: 'o1',
    title: '3-Month Extension',
    subtitle: 'Get 3 months for the price of 2.',
    badge: '33% OFF',
    color: '#FF6B00',
  },
  {
    id: 'o2',
    title: 'PT Bundle Pack',
    subtitle: '10 personal training sessions at discounted rate.',
    badge: 'SAVE ₹2000',
    color: '#9C27B0',
  },
  {
    id: 'o3',
    title: 'Bring a Friend',
    subtitle: 'Refer a friend and earn 500 Build Coins each.',
    badge: '+500 COINS',
    color: '#2196F3',
  },
];

export const activityData = {
  thisMonth: {
    visits: 18,
    caloriesEstimate: '12,400 kcal',
    daysActive: 18,
    streak: 5,
  },
  visitHistory: [
    { day: 'Mon', visited: true },
    { day: 'Tue', visited: true },
    { day: 'Wed', visited: false },
    { day: 'Thu', visited: true },
    { day: 'Fri', visited: true },
    { day: 'Sat', visited: true },
    { day: 'Sun', visited: false },
  ],
  weeklyVisits: [
    { week: 'W1', count: 4 },
    { week: 'W2', count: 5 },
    { week: 'W3', count: 3 },
    { week: 'W4', count: 6 },
  ],
};

export const complaintCategories = [
  'Equipment Issue',
  'Cleanliness',
  'Staff Behaviour',
  'Locker Issue',
  'Billing / Coins',
  'Cafe Order Issue',
  'Safety Concern',
  'Other',
];
